[i2c]
address = 0x40
path = "/dev/i2c-1"

[pwm]
prescale = 100

[[channel]]
pwm_channel = 0
min = 380
max = 620
neutral = 500
step = 20
mavlink_channel = 1

[[channel]]
pwm_channel = 1
min = 200
max = 600
step = 20
neutral = 400
mavlink_channel = 3

